<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/AssetImport/AssetImport.RAMCacheUtility.cs" Link="Production/AssetImport.RAMCacheUtility.cs" />
    <Compile Include="../../src/AssetImport/AssetImport.AssetSource.cs" Link="Production/AssetImport.AssetSource.cs" />
    <PackageReference Include="LitJson" Version="0.19.0" />
  </ItemGroup>
</Project>
